package com.infotexa.notificationservice.enumeration;

public enum EventType {
    REGISTRATION, RESETPASSWORD, USER_CREATED, ACCOUNT_VERIFIED , TICKET_CREATED , TICKET_ASSIGNED , TICKET_STATUS_CHANGED , TICKET_COMMENT_ADDED , TICKET_PRIORITY_CHANGED , TICKET_DELETED , USER_ROLE_CHANGED
     ,COMMENT_CREATED , COMMENT_DELETED , COMMENT_UPDATED , TICKET_UPDATED,
    FILE_UPLOADED , FILE_DELETED , NEW_MESSAGE , MESSAGE_DELETED , MESSAGE_UPDATED
}
