spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default-schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect

SERVER:
  PORT: 8087

JWKS:
  URI : https://auth-service.happyforest-b11122d9.francecentral.azurecontainerapps.io/oauth2/jwks

UI:
  APP:
    URL: http://localhost:3000/login