spring:
  application:
    name: gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  logging:
    level:
      org.springframework.security: DEBUG
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webmvc:
          routes:
            - id: authorization-server
              uri:  https://auth-service.happyforest-b11122d9.francecentral.azurecontainerapps.io
              predicates:
                - Path=/authorization/**
            - id: user-service
              uri: https://user-service.happyforest-b11122d9.francecentral.azurecontainerapps.io
              predicates:
                - Path=/user/**
            - id: ticket-service
              uri: https://ticket-service.happyforest-b11122d9.francecentral.azurecontainerapps.io
              predicates:
                - Path=/ticket/**
            - id: notification-service
              uri: https://notification-service.happyforest-b11122d9.francecentral.azurecontainerapps.io
              predicates:
                - Path=/notification/**
            - id: storage-service
              uri: https://storage-service.happyforest-b11122d9.francecentral.azurecontainerapps.io
              predicates:
                - Path=/storage/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: false
    service-url:
      defaultZone: http://${USER_NAME}:${PASSWORD}@${EUREKA_HOST}:5002/eureka/

server:
  port: ${SERVER_PORT}

jwks:
  uri: ${JWKS_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,mappings
  endpoint:
    gateway:
      access: unrestricted

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security: DEBUG