




spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default-schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect

SERVER:
  PORT: 8085

JWKS:
  URI : http://localhost:8080/oauth2/jwks

UI:
  APP:
    URL: http://localhost:3000/login



KAFKA:
  SERVER:
    URL: qouarknotificationhub.servicebus.windows.net:9093  # ← same URL here too!
