SPRING_PROFILES_ACTIVE: test

PRIVATE_KEY: "private.key"
PUBLIC_KEY: "public.key"

POSTGERS_USERNAME: user
POSTGERS_PASSWORD: password
POSTGRES_HOST: localhost
POSTGRES_DATABASE: localdb
POSTGRES_PORT: 5432

USER_NAME: admin
PASSWORD: password

SERVER_PORT: 8085

JWKS_URI : http://localhost:8080/oauth2/jwks


UI_APP_URL: http://localhost:3000/login

KAFKA_SERVER_URL: localhost:9092
