spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL:20.19.82.88:9092}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default-schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect


SERVER:
  PORT: 8088

MAIL:
  HOST: ${MAIL_HOST:smtp.gmail.com}
  PORT: ${MAIL_PORT:587}
  ID : ${MAIL_ID:bensariahazem@gmail.com}
  PASSWORD: ${MAIL_PASSWORD:sbynnbsuxszzgmup}


#MAIL_HOST: smtp.gmail.com
#MAIL_PORT: 587
#MAIL_ID: bensariahazem@gmail.com
#MAIL_PASSWORD: sbynnbsuxszzgmup

JWKS:
  URI : https://auth-service.happyforest-b11122d9.francecentral.azurecontainerapps.io/oauth2/jwks

UI_APP_URL: http://localhost:3000/login

KAFKA:
  SERVER:
    URL: 20.19.82.88:9092