spring:
  application:
    name: notificationservice
  cloud:
    discovery:
      enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE:localdb}
    username: ${POSTGRES_USERNAME:user}
    password: ${POSTGRES_PASSWORD:password}
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: POSTGRESQL
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default-schema: ${POSTGRES_DATABASE}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL:qouarknotificationhub.servicebus.windows.net:9093 }
    template:
      default-topic: NOTIFICATION_TOPIC
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: Notification:com.infotexa.notificationservice.domain.Notification
  thymeleaf:
    suffix: .html


  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}
    default-encoding: utf-8
    properties:
      mail:
        mime:
          charset: utf-8
        smtp:
          writetimeout: 10000
          connecttimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST:http://localhost:3000}

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: false
    service-url:
      defaultZone: http://${USER_NAME}:${PASSWORD}@${EUREKA_HOST}:5002/eureka/


ui:
    app:
      url: ${UI_APP_URL}


jwks:
    uri: ${JWKS_URI}

server:
  port: ${SERVER_PORT}