SPRING_PROFILES_ACTIVE: dev


POSTGRES_USERNAME: user
POSTGRES_PASSWORD: password
POSTGRES_HOST: localhost
POSTGRES_DATABASE: localdb
POSTGRES_PORT: 5432

USER_NAME: admin
PASSWORD: admin
SERVER_PORT: 5002
