SPRING_PROFILES_ACTIVE: prod

POSTGRES_USERNAME: user
POSTGRES_PASSWORD: password
POSTGRES_HOST: localhost
POSTGRES_DATABASE: localdb
POSTGRES_PORT: 5432

USER_NAME: admin
PASSWORD: admin
ROLES: EUREKA_CLIENT

SERVER_PORT: 5002
UI_APP_URL: http://localhost:3000/login